---
version: "3.9"
services:
    proxy:
        image: traefik:v2.5
        hostname: "${COMPOSE_PROJECT_NAME}-proxy"
        container_name: "${COMPOSE_PROJECT_NAME}_proxy"
        extra_hosts:
            - "host.dev:${HOST_IP}"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./etc/proxy/traefik.yaml:/etc/traefik/traefik.yaml:ro"
            - "./var/ssl-certs/${APP_HOST}.crt:/etc/ssl/certs/server.crt:ro"
            - "./var/ssl-certs/${APP_HOST}.key:/etc/ssl/private/server.key:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-proxy.rule=Host(`${COMPOSE_PROJECT_NAME}-proxy`, `${COMPOSE_PROJECT_NAME}-proxy.docker.localhost`, `${APP_HOST}`, `localhost`)"
        networks:
            hip_net:
                ipv4_address: 172.16.200.100
                aliases:
                    - "${APP_HOST}"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    web-server:
        image: nginx:1-alpine
        hostname: "${COMPOSE_PROJECT_NAME}-web-server"
        container_name: "${COMPOSE_PROJECT_NAME}_web-server"
        extra_hosts:
            - "host.dev:${HOST_IP}"
        ports:
            - "8888:80"
        volumes:
            - "./data:${DATA_DIR}"
        labels:
            - "traefik.enable=true" # make container visible for Traefik upstreaming
        depends_on:
            - php
        networks:
            hip_net:
                ipv4_address: 172.16.200.110
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    php:
        image: bravepickle/php:7.4-fpm-alpine-dev
        # platform: $OS_PLATFORM
        build:
            context: ./etc/php
            args:
                DATA_DIR: "${DATA_DIR}"
        hostname: "${COMPOSE_PROJECT_NAME}-php"
        container_name: "${COMPOSE_PROJECT_NAME}_php"
        extra_hosts:
            - "host.dev:${HOST_IP}"
        volumes:
            - "./data:${DATA_DIR}"
        depends_on:
            - db
            - redis
        networks:
            hip_net:
                ipv4_address: 172.16.200.120
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    php8:
        image: bravepickle/php:8-fpm-alpine-dev
        # platform: $OS_PLATFORM
        build:
            context: ./etc/php
            dockerfile: Dockerfile-php8
            args:
                DATA_DIR: "${DATA_DIR}"
        hostname: "${COMPOSE_PROJECT_NAME}-php8"
        container_name: "${COMPOSE_PROJECT_NAME}_php8"
        extra_hosts:
            - "host.dev:${HOST_IP}"
        volumes:
            - "./data:${DATA_DIR}"
        depends_on:
            - db
            - redis
        networks:
            hip_net:
                ipv4_address: 172.16.200.121
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    db:
        image: percona:5.7
        # platform: $OS_PLATFORM
        hostname: "${COMPOSE_PROJECT_NAME}-db"
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASS}"
        networks:
            hip_net:
                ipv4_address: 172.16.200.130
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    redis:
        image: redis:6-alpine
        # platform: $OS_PLATFORM
        hostname: "${COMPOSE_PROJECT_NAME}-redis"
        container_name: "${COMPOSE_PROJECT_NAME}_redis"
        networks:
            hip_net:
                ipv4_address: 172.16.200.140
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    proxy-test:
        image: traefik/whoami
        # platform: $OS_PLATFORM
        hostname: "${COMPOSE_PROJECT_NAME}-proxy-test"
        container_name: "${COMPOSE_PROJECT_NAME}_proxy_test"
        depends_on:
            - proxy
        labels:
            - "traefik.enable=true"
            # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-proxy-test.rule=Host(`${COMPOSE_PROJECT_NAME}-proxy-test`, `${COMPOSE_PROJECT_NAME}-proxy-test.docker.localhost`)"
        networks:
            hip_net:
                ipv4_address: 172.16.200.200
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

networks:
    hip_net:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 172.16.200.0/24
