---
version: "3.9"
services:
    proxy:
        image: traefik:v2.5
        hostname: "${COMPOSE_PROJECT_NAME}-proxy"
        container_name: "${COMPOSE_PROJECT_NAME}_proxy"
        extra_hosts:
            - "master.dev:${MASTER_HOST}"
        ports:
            - "80:80"
            # - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            # - "./etc/proxy/traefik.yaml:/etc/traefik/traefik.yaml"
        # depends_on:
        #     - web-server
        command: --api.insecure=true --providers.docker
        labels:
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_proxy.rule=Host(`${COMPOSE_PROJECT_NAME}-proxy`, `${COMPOSE_PROJECT_NAME}-proxy.docker.localhost`, `${COMPOSE_PROJECT_NAME}.localhost`)"
        networks:
            hip_net:
                ipv4_address: 172.16.200.100
                aliases:
                    - "${COMPOSE_PROJECT_NAME}.localhost"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    web-server:
        image: nginx:1-alpine
        hostname: "${COMPOSE_PROJECT_NAME}-web-server"
        container_name: "${COMPOSE_PROJECT_NAME}_web-server"
        extra_hosts:
            - "master.dev:${MASTER_HOST}"
        ports:
            - "8888:80"
        volumes:
            - "./data:${DATA_DIR}"
        depends_on:
            - php
        networks:
            hip_net:
                ipv4_address: 172.16.200.110
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    php:
        image: php:7.4-fpm-alpine
        hostname: "${COMPOSE_PROJECT_NAME}-php"
        container_name: "${COMPOSE_PROJECT_NAME}_php"
        extra_hosts:
            - "master.dev:${MASTER_HOST}"
        volumes:
            - "./data:${DATA_DIR}"
        depends_on:
            - db
            - redis
        networks:
            hip_net:
                ipv4_address: 172.16.200.120
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    db:
        image: percona:5.7
        hostname: "${COMPOSE_PROJECT_NAME}-db"
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        networks:
            hip_net:
                ipv4_address: 172.16.200.130
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    redis:
        image: redis:6-alpine
        hostname: "${COMPOSE_PROJECT_NAME}-redis"
        container_name: "${COMPOSE_PROJECT_NAME}_redis"
        networks:
            hip_net:
                ipv4_address: 172.16.200.140
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    proxy-test:
        image: traefik/whoami
        hostname: "${COMPOSE_PROJECT_NAME}-proxy-test"
        container_name: "${COMPOSE_PROJECT_NAME}_proxy_test"
        depends_on:
            - proxy
        networks:
            hip_net:
                ipv4_address: 172.16.200.200
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

networks:
    hip_net:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 172.16.200.0/24
