# Settings for dynamic config file provider
# See https://doc.traefik.io/traefik/providers/file/
# See https://medium.com/@clintcolding/use-your-own-certificates-with-traefik-a31d785a6441

# Self-signed SSL certificates can be defined only using file provider
tls:
    certificates:
        -   certFile: /etc/ssl/certs/server.crt
            keyFile: /etc/ssl/private/server.key

# When testing certs, enable this so traefik doesn't use
# it's own self signed. By default if it can't find a matching
# cert, it'll just create it's own which will cause cert warnings
# in browser
  # options:
    # default:
      # sniStrict: true


# TODO: add middlewares here and then set labels

http:
    middlewares:
        app-prefix:
            addPrefix:
                prefix: "/admin"
        # https-redirect:
        #   redirectScheme:
        #     scheme: https
        default-headers:
            headers:
                frameDeny: true
                sslRedirect: true
                browserXssFilter: true
                contentTypeNosniff: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 15552000
                customFrameOptionsValue: SAMEORIGIN
                customResponseHeaders:
                    X-Boo: dolor
                customRequestHeaders:
                    # X-Forwarded-Proto: https
                    X-App: lorem
                    X-Neo: ipsum
                accessControlAllowMethods: "GET,OPTIONS,PUT,DELETE,POST"
                accessControlAllowOriginList: "https://hipster.localhost,https://hipster.docker.localhost,https://localhost"
                accessControlMaxAge: 100
                addVaryHeader: true
                isDevelopment: true
                allowedHosts:
                    - hipster.localhost
                    - hipster.docker.localhost
                    - localhost

