---
# Docker configuration backend
# see https://doc.traefik.io/traefik/providers/docker/ for options
providers:
    docker:
        # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`, `{{ trimPrefix `/` .Name }}`, `hipster.localhost`)"

        # if enabled container for Traefik and rule not specified then this one will be used
        defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`, `{{ trimPrefix `/` .Name }}`)"

        # by default
        exposedByDefault: false

        # SSL setup
        # tls:
        #     ca: /etc/ssl/certs/server.crt
        #     key: /etc/ssl/private/server.key
        #     insecureSkipVerify: true # for development mode only!


# API and dashboard configuration
api:
    insecure: true

# http:
#   routers:
#     my-router:
#       rule: "Path(`/foo`)"
#       service: proxy-text

#     # proxy:
#     #   rule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`, `{{ trimPrefix `/` .Name }}`)"

#     proxy-test:
#       rule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`, `{{ trimPrefix `/` .Name }}`)"
#       service: proxy-test
#         # - proxy
#         # - proxy-test


# services:
#     # Define how to reach an existing service on our infrastructure
#     proxy-test:
#       loadBalancer:
#         servers:
#             - url: http://proxy-test-hip.docker.localhost
